spring:
  application:
    name: good-golems
  ai:
    vectorstore:
      redis:
        uri: redis://3.121.160.69:6379
    bedrock:
      aws:
        region: eu-central-1
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      cohere:
        chat:
          enabled: false
        embedding:
          enabled: true
      anthropic3:
        chat:
          enabled: true
          model: anthropic.claude-3-sonnet-20240229-v1:0
springdoc:
  api-docs:
    path: /api-docs